ADMINISTRATOR_DISPLAY_NAME=Administrator
ADMINISTRATOR_NAME=${ADMIN_NAME} 
ADMINISTRATOR_PASSWORD=${ADMIN_PASSWORD}
ADMINISTRATOR_EMAIL=jira.tvb@gmail.com
ADMINISTRATORS_GROUP=group-TVB-admins
KEYCLOAK_CONFIGURATION=/home/keycloak_config/keycloak_config.json
KEYCLOAK_WEB_CONFIGURATION=/home/keycloak_config/keycloak_config.json
ENABLE_KEYCLOAK_LOGIN=True
TVB_STORAGE=/home/TVB_STORAGE 
USR_DISK_SPACE=5242880
SELECTED_DB=postgres
URL_VALUE=postgresql+psycopg2://postgres:root@pod-db.${NAMESPACE}.svc.cluster.local:5432/tvb_hbp_database?user=${USER}&password=${PASSWORD}
WEB_SERVER_PORT=8080
CLUSTER_SCHEDULER=oar
MAXIMUM_NR_OF_THREADS=4
OP_BACKGROUND_JOB_INTERVAL=30
MAXIMUM_NR_OF_OPS_IN_RANGE=2000
MAXIMUM_NR_OF_VERTICES_ON_SURFACE=300000
DEPLOY_CLUSTER=False
LAST_CHECKED_FILE_VERSION=5
LAST_CHECKED_CODE_VERSION=18157
TRACE_USER_ACTIONS=False
RUN_ON_HPC=False
HPC_COMPUTE_SITE=DAINT-CSCS
CRYPT_DATADIR=/home/.data
CRYPT_PASSDIR=/home/.pass
ENCRYPT_STORAGE=False
DECRYPT_PATH=/home/DECRYPT
MAX_CONNECTIONS=20
MAX_ASYNC_CONNECTION=2
FILE_STORAGE=h5
ELASTICSEARCH_URL=https://elk-cscs.tc.humanbrainproject.eu:9200
ELASTICSEARCH_API_KEY=
ELASTICSEARCH_LOGGING_INDEX=app_tvb_logging
ELASTICSEARCH_REQUEST_TIMEOUT=30
ELASTICSEARCH_BUFFER_THRESHOLD=1000000
OPENSHIFT_DEPLOY=True
OPENSHIFT_NAMESPACE=thevirtualbrain
OPENSHIFT_APPLICATION=thevirtualbrain
#PROCESSING_OPERATIONS_APPLICATION=process-operations
#DATA_ENCRYPTION_HANDLER_APPLICATION=thevirtualbrain

#
#   CONFIGS RELATED TO KUBERNETES CLOUD DEPLOYMENTS
#
#   TRUE IF IT IS A KS DEPLOYMENT
IS_CLOUD_DEPLOY=True
IS_CLOUD_HTTPS=False
#   KUBERNETES DNS LOCAL NAME FOR THE OPERATIONS PROCESSING POD
PROCESSING_OPERATIONS_APPLICATION=pod-exec.${NAMESPACE}.svc.cluster.local
PROCESSING_OPERATIONS_PODS_MAX_NO=2
#   KUBERNETES DNS LOCAL NAME FOR DATA ENCRYPTION HANDLING
DATA_ENCRYPTION_HANDLER_APPLICATION=pod-web.${NAMESPACE}.svc.cluster.local