name: docker-based library testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: satackey/action-docker-layer-caching@v0.0.8

      - name: Build image
        run: cd scientific_library && docker build -t tvb/lib .

      - name: Run tests
        run: >
          docker run --rm -v $PWD:/work -w /work tvb/lib pytest -n4
