name: Build image
on: [push]
jobs:

  smoke-test:
    runs-on: mrs-ci
    steps:

      - name: echo test
        run: echo test

      - name: nvidia-smi test
        run: nvidia-smi

      - name: pycuda test
        run: python -c "import pycuda.autoinit; print('yes')"


  pytests:
    runs-on: mrs-ci
    steps:
      - uses: actions/checkout@v1
      - name: debug debug
        run: env && pwd && ls -lh
      - name: run pytest
        run: cd scientific_library && pytest

# name: Run tests (GitHub CI)
# on: [push]
# jobs:
#   pytest:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.7]

#     steps:
#       - uses: actions/checkout@v1

#       - name: set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v2
#         with:
#           python-version: ${{ matrix.python-version }}
      
#       - name: upgrade pip
#         run: python -m pip install --upgrade pip

#       - name: put ~/.local/bin on $PATH
#         run: echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

#       - name: create a requirements file
#         run: echo "numba scipy numpy networkx scikit-learn cython numexpr psutil pytest pytest-cov pytest-xdist pytest-benchmark pytest-mock matplotlib psycopg2 h5py>=2.10 typing BeautifulSoup4 subprocess32 flask-restplus python-keycloak mako pyAesCrypt pyunicore formencode cfflib jinja2 nibabel sqlalchemy alembic allensdk sphinx==1.2.3 docutils==0.12 werkzeug==0.16.1 flask gevent jupyter cherrypy" | tr ' ' \\n > requirements.txt

#       - name: cache ~/.local for pip deps
#         id: cache-local
#         uses: actions/cache@v2
#         with:
#           path: ~/.local
#           key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

#       - name: pip install dependencies (from Dockerfile-build)
#         if: steps.cache-local.outputs.cache-hit != 'true'
#         run: |
#           pip install --user -r requirements.txt
#           pip install --user --no-build-isolation tvb-gdist

#       - name: setup tvb
#         run: cd tvb_build && bash install_full_tvb.sh

#       - name: cache data
#         id: cache-data
#         uses: actions/cache@v2
#         with:
#           path: tvb_data
#           key: tvb-data

#       - name: download data
#         if: steps.cache-data.outputs.cache-hit != 'true'
#         run: |
#           wget -q https://zenodo.org/record/4263723/files/tvb_data.zip?download=1 -O tvb_data.zip
#           mkdir tvb_data
#           unzip tvb_data.zip -d tvb_data
#           rm tvb_data.zip

#       - name: setup data
#         run: |
#           cd tvb_data
#           python3 setup.py develop

#       - name: run library tests
#         run: cd scientific_library && pytest -n4

#       - name: run framework tests
#         run: cd framework_tvb && pytest
